language: python
python: 3.6
install: 
 #  - pip install .
   - pip install -r requirements.txt
   - pip install coveralls
   - pip install coverage
script: 
   - python -m unittest test_rpn
   - coverage run ./test_rpn.py
  # - coverage help
after_success: coveralls
 
