language: python
python: 3.6
install: 
 #  - pip install .
   - pip install -r requirements.txt
   - pip install coveralls
script: 
   - python -m unittest test_rpn
   - coverage run --source=python -m unittest test_rpn
   - coverage help
after_success: coveralls
 
